<template>
  <Loading :active="LoadingState">
    <div class="loadingio-spinner-ripple-3xq5u6jldre">
      <div class="ldio-dwik2dnj2i">
        <div></div>
        <div></div>
      </div>
    </div>
  </Loading>
</template>

<script>
import Loading from 'vue-loading-overlay';

export default {
  props: {
    LoadingState: {
      type: Boolean
    }
  },
  components: {
    Loading
  }
};
</script>

<style lang="scss">
@import '~vue-loading-overlay/dist/vue-loading.css';
//Loading
@keyframes ldio-dwik2dnj2i {
  0% {
    top: 70px;
    left: 70px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: -15px;
    left: -15px;
    width: 170px;
    height: 170px;
    opacity: 0;
  }
}
.ldio-dwik2dnj2i div {
  position: absolute;
  border-width: 30px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-dwik2dnj2i 2.5s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.ldio-dwik2dnj2i div:nth-child(1) {
  border-color: #1d0e0b;
  animation-delay: 0s;
}
.ldio-dwik2dnj2i div:nth-child(2) {
  border-color: #774023;
  animation-delay: -1.25s;
}
.loadingio-spinner-ripple-3xq5u6jldre {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-dwik2dnj2i {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-dwik2dnj2i div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
